"""fix the bugs in rider_application

Revision ID: 1338daf571cf
Revises: 7f9441323a92
Create Date: 2026-06-18 16:50:26.925843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1338daf571cf"
down_revision: Union[str, Sequence[str], None] = "7f9441323a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rider_applications", sa.Column("city_id", sa.Uuid(), nullable=False))
    op.add_column(
        "rider_applications",
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "rider_applications",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_type",
        existing_type=postgresql.ENUM("AADHAAR", "PAN", name="identityprooftype"),
        nullable=True,
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_number",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=512),
        nullable=True,
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_image",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "rider_applications", "profile_image", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "rider_applications",
        "vehicle_type",
        existing_type=postgresql.ENUM("BIKE_SCOOTER", "EV", name="vehicletype"),
        nullable=True,
    )
    op.alter_column(
        "rider_applications",
        "vehicle_number",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "rider_applications",
        "license_number",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=512),
        nullable=True,
    )
    op.alter_column(
        "rider_applications",
        "license_expiry_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        nullable=True,
    )
    op.alter_column(
        "rider_applications", "license_image", existing_type=sa.TEXT(), nullable=True
    )
    op.create_index(
        "uq_rider_applications_active_per_user",
        "rider_applications",
        ["applicant_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('APPROVED', 'REJECTED')"),
    )
    op.create_foreign_key(None, "rider_applications", "cities", ["city_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rider_applications", type_="foreignkey")
    op.drop_index(
        "uq_rider_applications_active_per_user",
        table_name="rider_applications",
        postgresql_where=sa.text("status NOT IN ('APPROVED', 'REJECTED')"),
    )
    op.alter_column(
        "rider_applications", "license_image", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "rider_applications",
        "license_expiry_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "rider_applications",
        "license_number",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "rider_applications",
        "vehicle_number",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "rider_applications",
        "vehicle_type",
        existing_type=postgresql.ENUM("BIKE_SCOOTER", "EV", name="vehicletype"),
        nullable=False,
    )
    op.alter_column(
        "rider_applications", "profile_image", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_image",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_number",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "rider_applications",
        "identity_proof_type",
        existing_type=postgresql.ENUM("AADHAAR", "PAN", name="identityprooftype"),
        nullable=False,
    )
    op.drop_column("rider_applications", "updated_at")
    op.drop_column("rider_applications", "submitted_at")
    op.drop_column("rider_applications", "city_id")
    # ### end Alembic commands ###
