"""(rider) added rider earning  and payout model

Revision ID: 2ea013a837a3
Revises: 8b63d008bd5c
Create Date: 2026-06-21 02:39:07.777284

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ea013a837a3"
down_revision: Union[str, Sequence[str], None] = "8b63d008bd5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rider_id", sa.Uuid(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="payoutstatus"
            ),
            nullable=False,
        ),
        sa.Column("provider_payout_id", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("period_end > period_start", name="ck_payout_period_valid"),
        sa.CheckConstraint("total_amount > 0", name="ck_payout_total_amount_positive"),
        sa.ForeignKeyConstraint(["rider_id"], ["riders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_payout_id"),
        sa.UniqueConstraint(
            "rider_id", "period_start", "period_end", name="uq_payout_rider_period"
        ),
    )
    op.create_index(op.f("ix_payouts_rider_id"), "payouts", ["rider_id"], unique=False)
    op.create_index(op.f("ix_payouts_status"), "payouts", ["status"], unique=False)
    op.create_table(
        "rider_earnings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rider_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID_OUT", "REVERSED", name="earningstatus"),
            nullable=False,
        ),
        sa.Column("payout_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_rider_earning_amount_positive"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
        ),
        sa.ForeignKeyConstraint(["rider_id"], ["riders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_index(
        "idx_rider_earnings_rider_status",
        "rider_earnings",
        ["rider_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_earnings_payout_id"),
        "rider_earnings",
        ["payout_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_earnings_rider_id"), "rider_earnings", ["rider_id"], unique=False
    )
    op.create_index(
        op.f("ix_rider_earnings_status"), "rider_earnings", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rider_earnings_status"), table_name="rider_earnings")
    op.drop_index(op.f("ix_rider_earnings_rider_id"), table_name="rider_earnings")
    op.drop_index(op.f("ix_rider_earnings_payout_id"), table_name="rider_earnings")
    op.drop_index("idx_rider_earnings_rider_status", table_name="rider_earnings")
    op.drop_table("rider_earnings")
    op.drop_index(op.f("ix_payouts_status"), table_name="payouts")
    op.drop_index(op.f("ix_payouts_rider_id"), table_name="payouts")
    op.drop_table("payouts")
    # ### end Alembic commands ###
