"""enable postgis

Revision ID: 3ea16726381f
Revises: b79fc83e7a6d
Create Date: 2026-06-21 18:49:35.313176

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ea16726381f"
down_revision: Union[str, Sequence[str], None] = "b79fc83e7a6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_payments_provider_refund_id"), "payments", type_="unique"
    )
    op.drop_column("payments", "refund_failure_reason")
    op.drop_column("payments", "provider_refund_id")
    op.drop_column("payments", "refund_initiated_at")

    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "refund_initiated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "provider_refund_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "refund_failure_reason",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        op.f("uq_payments_provider_refund_id"),
        "payments",
        ["provider_refund_id"],
        postgresql_nulls_not_distinct=False,
    )

    op.execute("DROP EXTENSION IF EXISTS postgis")
    # ### end Alembic commands ###
