"""(riders) added riders model

Revision ID: 6b2380a91a1e
Revises: 09261014cf0d
Create Date: 2026-06-19 14:56:22.699025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b2380a91a1e"
down_revision: Union[str, Sequence[str], None] = "09261014cf0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "riders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("profile_image", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="riderprofilestatus"),
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("current_latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column(
            "current_longitude", sa.Numeric(precision=10, scale=7), nullable=True
        ),
        sa.Column("last_location_update", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "vehicle_type",
            postgresql.ENUM(
                "BIKE_SCOOTER",
                "EV",
                name="vehicletype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("vehicle_number", sa.String(length=50), nullable=True),
        sa.Column("avg_rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("total_deliveries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_riders_available", "riders", ["is_online", "is_available"], unique=False
    )
    op.create_index(
        "idx_riders_location",
        "riders",
        ["current_latitude", "current_longitude"],
        unique=False,
    )
    op.create_index(op.f("ix_riders_status"), "riders", ["status"], unique=False)
    op.create_index(op.f("ix_riders_user_id"), "riders", ["user_id"], unique=True)
    op.create_index(
        op.f("ix_rider_applications_status"),
        "rider_applications",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rider_applications_status"), table_name="rider_applications")
    op.drop_index(op.f("ix_riders_user_id"), table_name="riders")
    op.drop_index(op.f("ix_riders_status"), table_name="riders")
    op.drop_index("idx_riders_location", table_name="riders")
    op.drop_index("idx_riders_available", table_name="riders")
    op.drop_table("riders")
    # ### end Alembic commands ###
