"""(menu) added updated at column to MenuCategory model

Revision ID: 78bf7a5b8451
Revises: 5f7748b14d08
Create Date: 2026-06-08 13:18:55.261351

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78bf7a5b8451"
down_revision: Union[str, Sequence[str], None] = "5f7748b14d08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # initially adding column as  nullable
    op.add_column(
        "menu_categories",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Backfill existing rows
    op.execute("""
        UPDATE menu_categories
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)

    # enforcing NOT NULL
    op.alter_column("menu_categories", "updated_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_categories", "updated_at")
    # ### end Alembic commands ###
