"""(locations) added new model to track the services in different cities

Revision ID: 7df34484fd84
Revises: 813b952b4983
Create Date: 2026-06-18 00:14:42.179981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7df34484fd84"
down_revision: Union[str, Sequence[str], None] = "813b952b4983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rider_applications",
        "identity_proof_number",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rider_applications",
        "identity_proof_number",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
