"""(notification) added supporting enums for order notification lifecycle and added City model

Revision ID: 7f9441323a92
Revises: 7df34484fd84
Create Date: 2026-06-18 15:30:01.753408

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f9441323a92"
down_revision: Union[str, Sequence[str], None] = "7df34484fd84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="citystatus"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("inactivated_by", sa.Uuid(), nullable=True),
        sa.Column("inactivation_reason", sa.String(length=250), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inactivated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "state", name="uq_city_name_state"),
    )
    op.create_index(
        op.f("ix_cities_created_by"), "cities", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_cities_inactivated_by"), "cities", ["inactivated_by"], unique=False
    )
    op.create_index(op.f("ix_cities_status"), "cities", ["status"], unique=False)
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'CUISINE_APPROVED';"
    )
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'CUISINE_REJECTED';"
    )
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'CUISINE_REVOKED';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'ORDER_PREPARING';")
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'ORDER_READY_FOR_PICKUP';"
    )
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'RIDER_ASSIGNED';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'ORDER_PICKUPED';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'ORDER_DELIVERED';")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cities_status"), table_name="cities")
    op.drop_index(op.f("ix_cities_inactivated_by"), table_name="cities")
    op.drop_index(op.f("ix_cities_created_by"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
