"""(rider applications) added rider appliation model

Revision ID: 813b952b4983
Revises: ca56d3cabda3
Create Date: 2026-06-17 18:00:39.421006

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "813b952b4983"
down_revision: Union[str, Sequence[str], None] = "ca56d3cabda3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rider_applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "identity_proof_type",
            sa.Enum("AADHAAR", "PAN", name="identityprooftype"),
            nullable=False,
        ),
        sa.Column("identity_proof_number", sa.String(length=20), nullable=False),
        sa.Column("identity_proof_image", sa.Text(), nullable=False),
        sa.Column("profile_image", sa.Text(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum("BIKE_SCOOTER", "EV", name="vehicletype"),
            nullable=False,
        ),
        sa.Column("vehicle_number", sa.String(length=50), nullable=False),
        sa.Column("license_number", sa.String(length=50), nullable=False),
        sa.Column("license_expiry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("license_image", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_REVIEW", "APPROVED", "REJECTED", name="riderapplicationstatus"
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["applicant_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rider_application_applicant_created_at",
        "rider_applications",
        ["applicant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_applications_applicant_id"),
        "rider_applications",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_applications_status"),
        "rider_applications",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rider_applications_status"), table_name="rider_applications")
    op.drop_index(
        op.f("ix_rider_applications_applicant_id"), table_name="rider_applications"
    )
    op.drop_index(
        "idx_rider_application_applicant_created_at", table_name="rider_applications"
    )
    op.drop_table("rider_applications")
    # ### end Alembic commands ###
