"""added sorting supporting fields and fixed bugs in menu and restaurant models

Revision ID: 83d5f60aa86b
Revises: 898adea4150c
Create Date: 2026-06-07 21:45:01.636908

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83d5f60aa86b"
down_revision: Union[str, Sequence[str], None] = "898adea4150c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_restaurant_id_sort_order"), "menu_items", type_="unique"
    )
    op.create_unique_constraint(
        "uq_category_id_sort_order", "menu_items", ["category_id", "sort_order"]
    )
    op.add_column(
        "restaurant_cuisines", sa.Column("is_primary", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "uq_restaurant_one_primary_cuisine",
        "restaurant_cuisines",
        ["restaurant_id"],
        unique=True,
        postgresql_where=sa.text("is_primary IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_restaurant_one_primary_cuisine",
        table_name="restaurant_cuisines",
        postgresql_where=sa.text("is_primary IS true"),
    )
    op.drop_column("restaurant_cuisines", "is_primary")
    op.drop_constraint("uq_category_id_sort_order", "menu_items", type_="unique")
    op.create_unique_constraint(
        op.f("uq_restaurant_id_sort_order"),
        "menu_items",
        ["restaurant_id", "sort_order"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
