"""(Cart) dropped total_amount column and calculating cost from the item itself for single source of truth

Revision ID: 8580755ad399
Revises: a2b60ddba5dd
Create Date: 2026-06-12 16:20:33.999552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8580755ad399"
down_revision: Union[str, Sequence[str], None] = "a2b60ddba5dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_items", sa.Column("item_name", sa.String(length=255), nullable=False)
    )
    op.drop_index(op.f("ix_cart_items_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_menu_item_id"), table_name="cart_items")
    op.create_unique_constraint(
        "uq_cart_menu_item", "cart_items", ["cart_id", "menu_item_id"]
    )
    op.drop_column("cart_items", "total_price")
    op.drop_column("cart_items", "created_at")
    op.drop_index(op.f("ix_carts_id"), table_name="carts")
    op.drop_column("carts", "total_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carts",
        sa.Column(
            "total_amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_carts_id"), "carts", ["id"], unique=False)
    op.add_column(
        "cart_items",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "cart_items",
        sa.Column(
            "total_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_cart_menu_item", "cart_items", type_="unique")
    op.create_index(
        op.f("ix_cart_items_menu_item_id"), "cart_items", ["menu_item_id"], unique=False
    )
    op.create_index(op.f("ix_cart_items_id"), "cart_items", ["id"], unique=False)
    op.drop_column("cart_items", "item_name")
    # ### end Alembic commands ###
