"""initial schema

Revision ID: 898adea4150c
Revises:
Create Date: 2026-06-07 13:41:51.123695

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "898adea4150c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CUSTOMER", "RESTAURANT_OWNER", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "user_status",
            sa.Enum("ACTIVE", "DEACTIVATED", "SUSPENDED", name="userstatus"),
            nullable=False,
        ),
        sa.Column("is_account_verified", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_user_status"), "users", ["user_status"], unique=False
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("address_line_1", sa.String(length=255), nullable=False),
        sa.Column("address_line_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cuisine_request_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("cuisine_name", sa.String(length=120), nullable=False),
        sa.Column("cuisine_slug", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rejected_by", sa.Uuid(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["rejected_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cuisine_request_history_cuisine_name"),
        "cuisine_request_history",
        ["cuisine_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cuisine_request_history_id"),
        "cuisine_request_history",
        ["id"],
        unique=False,
    )
    op.create_table(
        "cuisine_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("cuisine_name", sa.String(length=120), nullable=False),
        sa.Column("cuisine_slug", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cuisine_slug"),
    )
    op.create_index(
        op.f("ix_cuisine_requests_cuisine_name"),
        "cuisine_requests",
        ["cuisine_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cuisine_requests_id"), "cuisine_requests", ["id"], unique=False
    )
    op.create_table(
        "cuisine_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("cuisine_name", sa.String(length=120), nullable=False),
        sa.Column("cuisine_slug", sa.String(length=120), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "REVOKED", name="cuisinestatus"), nullable=False
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=500), nullable=True),
        sa.Column("revoked_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cuisine_slug"),
    )
    op.create_index(
        op.f("ix_cuisine_types_cuisine_name"),
        "cuisine_types",
        ["cuisine_name"],
        unique=False,
    )
    op.create_index(op.f("ix_cuisine_types_id"), "cuisine_types", ["id"], unique=False)
    op.create_table(
        "partner_applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("fssai_license_number", sa.String(length=14), nullable=False),
        sa.Column("gst_number", sa.String(length=15), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="applicationstatus"),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["applicant_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_applicant_created_at",
        "partner_applications",
        ["applicant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_applications_applicant_id"),
        "partner_applications",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_applications_fssai_license_number"),
        "partner_applications",
        ["fssai_license_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_applications_gst_number"),
        "partner_applications",
        ["gst_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_applications_id"), "partner_applications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_partner_applications_status"),
        "partner_applications",
        ["status"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("fssai_license_number", sa.String(length=14), nullable=True),
        sa.Column("gst_number", sa.String(length=15), nullable=True),
        sa.Column("cuisine_type", sa.String(length=100), nullable=True),
        sa.Column(
            "veg_type", sa.Enum("VEG", "NON_VEG", name="vegtype"), nullable=False
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("address_line_1", sa.String(length=255), nullable=False),
        sa.Column("normalized_address_line_1", sa.String(length=255), nullable=False),
        sa.Column("address_line_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("normalized_city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("is_manually_closed", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "BASIC_INFO_ADDED",
                "DOCUMENTS_ADDED",
                "MENU_ADDED",
                "SUBMITTED",
                "ACTIVE",
                "SUSPENDED",
                name="restaurantstatus",
            ),
            nullable=False,
        ),
        sa.Column("is_submitted", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("avg_rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id",
            "normalized_name",
            "normalized_address_line_1",
            "normalized_city",
        ),
    )
    op.create_index(
        op.f("ix_restaurants_fssai_license_number"),
        "restaurants",
        ["fssai_license_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restaurants_gst_number"), "restaurants", ["gst_number"], unique=False
    )
    op.create_index(op.f("ix_restaurants_id"), "restaurants", ["id"], unique=False)
    op.create_index(
        op.f("ix_restaurants_latitude"), "restaurants", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_restaurants_longitude"), "restaurants", ["longitude"], unique=False
    )
    op.create_index(
        op.f("ix_restaurants_owner_id"), "restaurants", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_restaurants_slug"), "restaurants", ["slug"], unique=True)
    op.create_table(
        "carts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carts_id"), "carts", ["id"], unique=False)
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=True)
    op.create_table(
        "menu_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "DELETED", name="menucategorystatus"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=350), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("restaurant_id", "normalized_name"),
        sa.UniqueConstraint("restaurant_id", "sort_order"),
    )
    op.create_index(
        op.f("ix_menu_categories_id"), "menu_categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_categories_restaurant_id"),
        "menu_categories",
        ["restaurant_id"],
        unique=False,
    )
    op.create_table(
        "menu_item_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum("PRIMARY", "GALLERY", "THUMBNAIL", name="menuitemimagetype"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_item_images_id"), "menu_item_images", ["id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CUISINE_APPROVED",
                "CUISINE_REJECTED",
                "CUISINE_REVOKED",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["cuisine_request_history.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_name", sa.String(length=255), nullable=False),
        sa.Column("address_id", sa.Uuid(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLACED",
                "CONFIRMED",
                "PREPARING",
                "READY_FOR_PICKUP",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("delivery_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("PENDING", "PAID", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("STRIPE", "RAZORPAY", "COD", name="paymentprovider"),
            nullable=False,
        ),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(
        op.f("ix_orders_restaurant_id"), "orders", ["restaurant_id"], unique=False
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "restaurant_availability",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "OPEN_24_HOURS", name="availabilitystatus"),
            nullable=False,
        ),
        sa.Column("opening_time", sa.Time(), nullable=True),
        sa.Column("closing_time", sa.Time(), nullable=True),
        sa.Column("shift_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "\n            NOT (\n                status != 'OPEN'\n                AND (opening_time IS NOT NULL OR closing_time IS NOT NULL)\n            )\n            ",
            name="ck_non_open_times_null",
        ),
        sa.CheckConstraint(
            "\n            NOT (\n                status = 'OPEN'\n                AND (opening_time IS NULL OR closing_time IS NULL)\n            )\n            ",
            name="ck_open_requires_times",
        ),
        sa.CheckConstraint(
            "\n            NOT (\n                status = 'OPEN_24_HOURS'\n                AND shift_index != 0\n            )\n            ",
            name="ck_24hr_single_shift",
        ),
        sa.CheckConstraint(
            "\n            opening_time IS NULL\n            OR closing_time IS NULL\n            OR opening_time != closing_time\n            ",
            name="ck_no_zero_length_shift",
        ),
        sa.CheckConstraint(
            "day_of_week >= 0 AND day_of_week <= 6", name="ck_valid_day_of_week"
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "restaurant_id",
            "day_of_week",
            "shift_index",
            name="uq_restaurant_day_shift",
        ),
    )
    op.create_index(
        "ix_availability_restaurant_day",
        "restaurant_availability",
        ["restaurant_id", "day_of_week"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restaurant_availability_restaurant_id"),
        "restaurant_availability",
        ["restaurant_id"],
        unique=False,
    )
    op.create_table(
        "restaurant_closures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_closure_restaurant_ends",
        "restaurant_closures",
        ["restaurant_id", "ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restaurant_closures_restaurant_id"),
        "restaurant_closures",
        ["restaurant_id"],
        unique=False,
    )
    op.create_table(
        "restaurant_cuisines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("cuisine_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING_REVIEW", name="mappedcuisinestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "\n            (\n                (cuisine_id IS NOT NULL AND request_id IS NULL)\n                OR\n                (cuisine_id IS NULL AND request_id IS NOT NULL)\n            )\n            ",
            name="check_cuisine_or_request_only",
        ),
        sa.ForeignKeyConstraint(
            ["cuisine_id"],
            ["cuisine_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["cuisine_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "restaurant_id", "cuisine_id", name="uq_restaurant_cuisine"
        ),
        sa.UniqueConstraint(
            "restaurant_id", "request_id", name="uq_restaurant_request"
        ),
    )
    op.create_index(
        op.f("ix_restaurant_cuisines_id"), "restaurant_cuisines", ["id"], unique=False
    )
    op.create_table(
        "restaurant_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum(
                "RESTAURANT_PHOTO",
                "FOOD_GALLERY",
                "DINING_MENU",
                name="restaurantimagetype",
            ),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_restaurant_images_id"), "restaurant_images", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_restaurant_images_restaurant_id"),
        "restaurant_images",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        "unique_primary_per_restaurant",
        "restaurant_images",
        ["restaurant_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true"),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "DELETED", name="menuitemstatus"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discounted_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "veg_type", sa.Enum("VEG", "NON_VEG", name="vegtype"), nullable=False
        ),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("preparation_time_minutes", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["menu_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_id",
            "normalized_name",
            name="uq_menu_item_category_normalized_name",
        ),
        sa.UniqueConstraint(
            "restaurant_id", "sort_order", name="uq_restaurant_id_sort_order"
        ),
    )
    op.create_index(
        op.f("ix_menu_items_category_id"), "menu_items", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_menu_items_id"), "menu_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_menu_items_restaurant_id"),
        "menu_items",
        ["restaurant_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payment_provider",
            sa.Enum("STRIPE", "RAZORPAY", "COD", name="paymentprovider"),
            nullable=False,
        ),
        sa.Column("transaction_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("menu_item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("item_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False
    )
    op.create_index(op.f("ix_cart_items_id"), "cart_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_cart_items_menu_item_id"), "cart_items", ["menu_item_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("menu_item_id", sa.Uuid(), nullable=False),
        sa.Column("item_name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("item_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_cart_items_menu_item_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_table("payments")
    op.drop_index(op.f("ix_menu_items_restaurant_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_category_id"), table_name="menu_items")
    op.drop_table("menu_items")
    op.drop_index(
        "unique_primary_per_restaurant",
        table_name="restaurant_images",
        postgresql_where=sa.text("is_primary = true"),
    )
    op.drop_index(
        op.f("ix_restaurant_images_restaurant_id"), table_name="restaurant_images"
    )
    op.drop_index(op.f("ix_restaurant_images_id"), table_name="restaurant_images")
    op.drop_table("restaurant_images")
    op.drop_index(op.f("ix_restaurant_cuisines_id"), table_name="restaurant_cuisines")
    op.drop_table("restaurant_cuisines")
    op.drop_index(
        op.f("ix_restaurant_closures_restaurant_id"), table_name="restaurant_closures"
    )
    op.drop_index("ix_closure_restaurant_ends", table_name="restaurant_closures")
    op.drop_table("restaurant_closures")
    op.drop_index(
        op.f("ix_restaurant_availability_restaurant_id"),
        table_name="restaurant_availability",
    )
    op.drop_index(
        "ix_availability_restaurant_day", table_name="restaurant_availability"
    )
    op.drop_table("restaurant_availability")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_restaurant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_menu_item_images_id"), table_name="menu_item_images")
    op.drop_table("menu_item_images")
    op.drop_index(
        op.f("ix_menu_categories_restaurant_id"), table_name="menu_categories"
    )
    op.drop_index(op.f("ix_menu_categories_id"), table_name="menu_categories")
    op.drop_table("menu_categories")
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_index(op.f("ix_restaurants_slug"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_owner_id"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_longitude"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_latitude"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_id"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_gst_number"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_fssai_license_number"), table_name="restaurants")
    op.drop_table("restaurants")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_partner_applications_status"), table_name="partner_applications"
    )
    op.drop_index(op.f("ix_partner_applications_id"), table_name="partner_applications")
    op.drop_index(
        op.f("ix_partner_applications_gst_number"), table_name="partner_applications"
    )
    op.drop_index(
        op.f("ix_partner_applications_fssai_license_number"),
        table_name="partner_applications",
    )
    op.drop_index(
        op.f("ix_partner_applications_applicant_id"), table_name="partner_applications"
    )
    op.drop_index("idx_applicant_created_at", table_name="partner_applications")
    op.drop_table("partner_applications")
    op.drop_index(op.f("ix_cuisine_types_id"), table_name="cuisine_types")
    op.drop_index(op.f("ix_cuisine_types_cuisine_name"), table_name="cuisine_types")
    op.drop_table("cuisine_types")
    op.drop_index(op.f("ix_cuisine_requests_id"), table_name="cuisine_requests")
    op.drop_index(
        op.f("ix_cuisine_requests_cuisine_name"), table_name="cuisine_requests"
    )
    op.drop_table("cuisine_requests")
    op.drop_index(
        op.f("ix_cuisine_request_history_id"), table_name="cuisine_request_history"
    )
    op.drop_index(
        op.f("ix_cuisine_request_history_cuisine_name"),
        table_name="cuisine_request_history",
    )
    op.drop_table("cuisine_request_history")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_user_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
