"""(Restaurant) added paused_at and pause_reason

Revision ID: 8ccc04a91d16
Revises: f6ea835aa9df
Create Date: 2026-06-10 23:54:37.114677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ccc04a91d16"
down_revision: Union[str, Sequence[str], None] = "f6ea835aa9df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants", sa.Column("pause_reason", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "restaurants", sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "paused_at")
    op.drop_column("restaurants", "pause_reason")
    # ### end Alembic commands ###
