"""(Menu) added Review model and review related relationships in User and restaurant modules and fixed MenuItemImage model

Revision ID: a9de46d8300a
Revises: d354e7d13ec3
Create Date: 2026-06-09 16:53:31.141657

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9de46d8300a"
down_revision: Union[str, Sequence[str], None] = "d354e7d13ec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "order_id", name="uq_user_order_review"),
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=False)
    op.drop_index(op.f("ix_menu_item_images_item_sort"), table_name="menu_item_images")
    op.drop_index(
        op.f("uq_menu_item_one_primary_image"),
        table_name="menu_item_images",
        postgresql_where="(image_type = 'PRIMARY'::menuitemimagetype)",
    )
    op.drop_constraint(
        op.f("uq_menu_item_primary_image"), "menu_item_images", type_="unique"
    )
    op.create_index(
        "ix_menu_item_images_restaurant",
        "menu_item_images",
        ["restaurant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_menu_item_image", "menu_item_images", ["menu_item_id"]
    )
    op.drop_column("menu_item_images", "sort_order")
    op.drop_column("menu_item_images", "image_type")
    op.drop_column("menu_items", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items",
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "menu_item_images",
        sa.Column(
            "image_type",
            postgresql.ENUM(
                "PRIMARY", "GALLERY", "THUMBNAIL", name="menuitemimagetype"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "menu_item_images",
        sa.Column("sort_order", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uq_menu_item_image", "menu_item_images", type_="unique")
    op.drop_index("ix_menu_item_images_restaurant", table_name="menu_item_images")
    op.create_unique_constraint(
        op.f("uq_menu_item_primary_image"),
        "menu_item_images",
        ["menu_item_id", "image_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("uq_menu_item_one_primary_image"),
        "menu_item_images",
        ["menu_item_id"],
        unique=True,
        postgresql_where="(image_type = 'PRIMARY'::menuitemimagetype)",
    )
    op.create_index(
        op.f("ix_menu_item_images_item_sort"),
        "menu_item_images",
        ["menu_item_id", "sort_order"],
        unique=False,
    )
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
