"""(user) remove foreign key refference from refference id and make it a normal uuid column

Revision ID: d83046f43522
Revises: 83d5f60aa86b
Create Date: 2026-06-08 09:31:07.478205

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d83046f43522"
down_revision: Union[str, Sequence[str], None] = "83d5f60aa86b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("notifications_reference_id_fkey"), "notifications", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("notifications_reference_id_fkey"),
        "notifications",
        "cuisine_request_history",
        ["reference_id"],
        ["id"],
    )
    # ### end Alembic commands ###
