"""(order) added rider_id

Revision ID: d854c1e796c4
Revises: 8887cf1f934c
Create Date: 2026-06-20 00:12:04.568485

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d854c1e796c4"
down_revision: Union[str, Sequence[str], None] = "8887cf1f934c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("rider_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_orders_rider_id"), "orders", ["rider_id"], unique=False)
    op.create_foreign_key(None, "orders", "riders", ["rider_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_rider_id"), table_name="orders")
    op.drop_column("orders", "rider_id")
    # ### end Alembic commands ###
