"""(Restaurants) fixed RestaurantStatus enum types

Revision ID: f6ea835aa9df
Revises: 1c0c32f296d6
Create Date: 2026-06-10 16:01:07.282635

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6ea835aa9df"
down_revision: Union[str, Sequence[str], None] = "1c0c32f296d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE restaurantstatus ADD VALUE IF NOT EXISTS 'TIMINGS_ADDED';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
